export interface School {
  id: number;
  name: string;
  founded: number;
  location: string;
  motto: string;
  grades: string;
  gradeLevels: string[];
  languages: string[];
  highlights: string[];
  accreditations: string[];
  contact: { phone?: string; email?: string; website?: string };
  specialPrograms: string[];
  rating: number;
  students: string;
  description: string;
  image: string;
  logo: string;
}

export const schools: School[] = [
  { id: 1, name: 'Azm School', founded: 2010, location: 'Boulevard Fouad Chehab, Tripoli', motto: 'Leadership, Diversity, Team Spirit & Well-being', grades: 'Preschool – Grade 12', gradeLevels: ['Pre-school', 'Primary', 'Elementary', 'Secondary'], languages: ['French', 'English', 'Arabic'], highlights: ['Cognia Accredited — only school in North Lebanon', 'UNESCO Associated Schools Network member', 'Green School Label recipient', 'Full-Inclusion Learning Support Department'], accreditations: ['Cognia', 'AEFE', 'UNESCO', 'Microsoft Imagine Academy'], contact: { phone: '+961 (6) 448-600', email: 'info@azmschool.com', website: 'https://azmschool.edu.lb/' }, specialPrograms: ['Early Intervention Program', 'Multi-Tier System of Supports', 'Learning Disabilities Program', 'Full Inclusion Model'], rating: 4.8, students: '1,200+', description: 'Azm School, established in 2010 at the northern gateway of Tripoli, represents one of the most significant modern investments in the educational infrastructure of North Lebanon. As a co-educational institution, it bridges the gap between traditional national identity and global requirements.', image: '/schools/azm.png', logo: '/schools/azm-logo.png' },
  { id: 2, name: 'International School – Al Koura', founded: 1985, location: 'Fouad Sleiman Street, Beitroumine', motto: 'Linking Learning to Life', grades: 'Kindergarten – Grade 12', gradeLevels: ['Pre-school', 'Primary', 'Elementary', 'Secondary'], languages: ['English', 'Arabic', 'French'], highlights: ['Project-Based Learning curriculum', 'Lebanese Baccalaureate & High School Diploma', 'AP Honors Program', 'Special Programs & Education Department'], accreditations: ['Lebanese Ministry of Education', 'AMSI Group Member'], contact: { phone: '+961 6 405 021', email: 'info@is-koura.org', website: 'https://is-koura.org' }, specialPrograms: ['Project-Based Learning', 'AP Program', 'Counseling Services', 'Inclusive Education'], rating: 4.7, students: '1,500+', description: 'IS Koura stands as a premier example of the internationalized Lebanese school model, located on an expansive 43,000-square-meter campus in Beitroumine.', image: '/schools/is-koura.png', logo: '/schools/is-koura-logo.png' },
  { id: 3, name: 'Collège National Orthodoxe', founded: 1900, location: 'Rue Mar Elias, El Mina, Tripoli', motto: 'A Century of Intellectual Heritage', grades: 'Nursery – Grade 12', gradeLevels: ['Pre-school', 'Primary', 'Elementary', 'Secondary'], languages: ['French', 'Arabic'], highlights: ["Founded in 1900 — one of Lebanon's oldest schools", 'French & Lebanese Baccalaureate tracks', 'Family atmosphere with mentorship focus', 'Parallel classes for learning support'], accreditations: ['French Baccalaureate', 'Lebanese Baccalaureate'], contact: { phone: '+961 6 601 519', email: 'info@cno.school', website: 'https://cno.school/' }, specialPrograms: ['Parallel Classes', 'Psychomotricity Services', 'Psychotherapy', 'Socio-Familial Intervention'], rating: 4.6, students: '950', description: 'The Collège National Orthodoxe, commonly known as St. Elie, is a cornerstone of the educational landscape in the El Mina district of Tripoli, founded in 1900.', image: '/schools/cno.png', logo: '/schools/cno-logo.png' },
  { id: 4, name: 'Al Bayan Islamic School', founded: 1995, location: 'Tripoli & Beirut', motto: 'Faith, Innovation & Global Readiness', grades: 'Preschool – Grade 12', gradeLevels: ['Pre-school', 'Primary', 'Elementary', 'Secondary'], languages: ['Arabic', 'English', 'French'], highlights: ['Robotics & STEM Program', "Hifz Program (Qur'anic Memorization)", 'ProtectED Safety Education', 'SAT & DELF Preparation'], accreditations: ['Lebanese Program', 'American High School System', 'Hifz Certification'], contact: { phone: '+961 5 480 128', email: 'info@albayanschools.edu.lb' }, specialPrograms: ['STEM & Robotics', 'Hifz Program', 'ProtectED Curriculum', 'SAT/DELF Prep'], rating: 4.7, students: '2,000+', description: 'Al Bayan Islamic School merges high academic standards with Islamic ethics and traditions, empowering students to reach their full potential.', image: '/schools/bayan.png', logo: '/schools/bayan-logo.png' },
  { id: 5, name: 'Tripoli Evangelical School', founded: 1995, location: 'Ras Maska, Koura', motto: 'Positive Change Agents', grades: 'Preschool – Grade 12', gradeLevels: ['Pre-school', 'Primary', 'Elementary', 'Secondary'], languages: ['English', 'Arabic', 'French'], highlights: ['Christian values-based education', 'Strong English-language program', 'Community service focus', 'Modern campus in Koura'], accreditations: ['Lebanese Baccalaureate', 'High School Diploma'], contact: { phone: '+961 6 411 000', website: 'https://tes.edu.lb' }, specialPrograms: ['Values Education', 'English Immersion', 'Community Service', 'Arts & Sports'], rating: 4.6, students: '1,000+', description: 'Tripoli Evangelical School educates students as positive change agents, combining Christian values with rigorous academics in the Koura region.', image: '/schools/evangelical.png', logo: '/schools/evangelical-logo.png' },
  { id: 6, name: 'David Karam Educational Center', founded: 1941, location: 'Samrieh, En Nakhle', motto: 'Unity Through Education', grades: 'Nursery – Grade 12', gradeLevels: ['Pre-school', 'Primary', 'Elementary', 'Secondary'], languages: ['Arabic', 'French', 'English'], highlights: ['Secular institution founded on unity principles', 'Four baccalaureate options including IB', 'Top-ranking university admission results', 'Inclusive special needs support'], accreditations: ['Lebanese Baccalaureate', 'French Baccalaureate', 'Freshman BA', 'International Baccalaureate'], contact: { phone: '+961 6 415 056', email: 'karam@cyberia.net.lb' }, specialPrograms: ['International Baccalaureate', 'Four BA Tracks', 'Trilingual Excellence', 'Special Needs Support'], rating: 4.8, students: '1,100+', description: 'DKEC is historically unique in North Lebanon for its foundational commitment to non-discriminatory, secular education.', image: '/schools/david-karam.jpg', logo: '/schools/david-karam-logo.png' },
  { id: 7, name: 'Collège des Frères – Deddeh', founded: 1892, location: 'Deddeh, Al-Koura', motto: 'Legacy of LaSalle Education', grades: 'Early Childhood – Grade 12', gradeLevels: ['Pre-school', 'Primary', 'Elementary', 'Secondary'], languages: ['French', 'Arabic'], highlights: ['132 years of educational history', 'De La Salle International Network', 'Classic disciplined academic environment', 'Strong alumni network'], accreditations: ['French Baccalaureate', 'Lebanese Baccalaureate'], contact: { phone: '+961 6 415 056', website: 'https://www.freresdd.edu.lb' }, specialPrograms: ['Classic Academic Track', 'De La Salle Values', 'Technology Integration', 'Alumni Network'], rating: 4.7, students: '1,300+', description: 'Collège des Frères in Deddeh belongs to the international network of De La Salle schools, with over 132 years of educational excellence.', image: '/schools/freres.png', logo: '/schools/freres-logo.png' },
  { id: 8, name: 'Rawdat al Fayhaa', founded: 1945, location: 'Dam W Farz & Miten, Tripoli', motto: 'Intellectual Curiosity, Tolerance & Lifelong Learning', grades: 'Preschool – Grade 12', gradeLevels: ['Pre-school', 'Primary', 'Elementary', 'Secondary'], languages: ['French', 'English', 'Arabic'], highlights: ['4,000+ students — largest school in North Lebanon', 'Cognia Accreditation', 'Dual French & English sections', 'State-of-the-art facilities'], accreditations: ['Cognia', 'Lebanese Baccalaureate', 'French Baccalaureate'], contact: { phone: '+961 6 412 402', email: 'info@rfs.edu.lb', website: 'https://www.rawdafayha.edu.lb' }, specialPrograms: ['Active Learning', 'Service Learning', 'Dual Programs', 'Sports & Arts Center'], rating: 4.8, students: '4,000+', description: 'Rawdat al Fayhaa has evolved from a small Francophone kindergarten into one of the largest and most prestigious private schools in Lebanon.', image: '/schools/fayhaa.png', logo: '/schools/fayhaa-logo.png' },
];

export const schoolLanguages = ['All', 'English', 'French', 'Arabic'];
